//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34209
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrangeEndless {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BuildingsIntroductionResourse {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BuildingsIntroductionResourse() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OrangeEndless.BuildingsIntroductionResourse", typeof(BuildingsIntroductionResourse).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 鼠标的指针~不是C里面的那个~可以帮你点击那个写着“摇”的按钮 的本地化字符串。
        /// </summary>
        public static string R1 {
            get {
                return ResourceManager.GetString("R1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 这绝不是一本仅仅包含爱意的小说，它还饱含着橘子 的本地化字符串。
        /// </summary>
        public static string R10 {
            get {
                return ResourceManager.GetString("R10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 折射出橘子 的本地化字符串。
        /// </summary>
        public static string R11 {
            get {
                return ResourceManager.GetString("R11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 香甜的橘子可以诱惑一些正在玩锑尔号的小学生来帮你摇树 的本地化字符串。
        /// </summary>
        public static string R2 {
            get {
                return ResourceManager.GetString("R2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 农场里可以出产橘子~只是在冬天需要水结冰来拯救橘子们 的本地化字符串。
        /// </summary>
        public static string R3 {
            get {
                return ResourceManager.GetString("R3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 这是专业生产橘子的工厂 的本地化字符串。
        /// </summary>
        public static string R4 {
            get {
                return ResourceManager.GetString("R4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 矿井里面可以挖出还没有变成化石的橘子 的本地化字符串。
        /// </summary>
        public static string R5 {
            get {
                return ResourceManager.GetString("R5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Oh!这里有一个由橘子组成的星球！ 的本地化字符串。
        /// </summary>
        public static string R6 {
            get {
                return ResourceManager.GetString("R6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 祖传克隆橘子！！！ 的本地化字符串。
        /// </summary>
        public static string R7 {
            get {
                return ResourceManager.GetString("R7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开存放橘子的仓库的大门 的本地化字符串。
        /// </summary>
        public static string R8 {
            get {
                return ResourceManager.GetString("R8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 带你重回橘子统治世界的时代 的本地化字符串。
        /// </summary>
        public static string R9 {
            get {
                return ResourceManager.GetString("R9", resourceCulture);
            }
        }
    }
}
