//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34209
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrangeEndless {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BuildingsStartCpsResourse {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BuildingsStartCpsResourse() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OrangeEndless.BuildingsStartCpsResourse", typeof(BuildingsStartCpsResourse).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 0.1 的本地化字符串。
        /// </summary>
        public static string R1 {
            get {
                return ResourceManager.GetString("R1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1000000 的本地化字符串。
        /// </summary>
        public static string R10 {
            get {
                return ResourceManager.GetString("R10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 100000000 的本地化字符串。
        /// </summary>
        public static string R11 {
            get {
                return ResourceManager.GetString("R11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 0.5 的本地化字符串。
        /// </summary>
        public static string R2 {
            get {
                return ResourceManager.GetString("R2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 4 的本地化字符串。
        /// </summary>
        public static string R3 {
            get {
                return ResourceManager.GetString("R3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 10 的本地化字符串。
        /// </summary>
        public static string R4 {
            get {
                return ResourceManager.GetString("R4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 40 的本地化字符串。
        /// </summary>
        public static string R5 {
            get {
                return ResourceManager.GetString("R5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 100 的本地化字符串。
        /// </summary>
        public static string R6 {
            get {
                return ResourceManager.GetString("R6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 400 的本地化字符串。
        /// </summary>
        public static string R7 {
            get {
                return ResourceManager.GetString("R7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 6000 的本地化字符串。
        /// </summary>
        public static string R8 {
            get {
                return ResourceManager.GetString("R8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 100000 的本地化字符串。
        /// </summary>
        public static string R9 {
            get {
                return ResourceManager.GetString("R9", resourceCulture);
            }
        }
    }
}
