//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrangeEndless {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BuildingsIntroductionResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BuildingsIntroductionResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OrangeEndless.BuildingsIntroductionResource", typeof(BuildingsIntroductionResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 鼠标的指针~不是C里面的那个~可以帮你点击那个写着“摇”的按钮.
        /// </summary>
        public static string R1 {
            get {
                return ResourceManager.GetString("R1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 这绝不是一本仅仅包含爱意的小说，它还饱含着橘子.
        /// </summary>
        public static string R10 {
            get {
                return ResourceManager.GetString("R10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 折射出橘子.
        /// </summary>
        public static string R11 {
            get {
                return ResourceManager.GetString("R11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 香甜的橘子可以诱惑一些正在玩锑尔号的小学生来帮你摇树.
        /// </summary>
        public static string R2 {
            get {
                return ResourceManager.GetString("R2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 农场里可以出产橘子~只是在冬天需要水结冰来拯救橘子们.
        /// </summary>
        public static string R3 {
            get {
                return ResourceManager.GetString("R3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 这是专业生产橘子的工厂.
        /// </summary>
        public static string R4 {
            get {
                return ResourceManager.GetString("R4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 矿井里面可以挖出还没有变成化石的橘子.
        /// </summary>
        public static string R5 {
            get {
                return ResourceManager.GetString("R5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oh!这里有一个由橘子组成的星球！.
        /// </summary>
        public static string R6 {
            get {
                return ResourceManager.GetString("R6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 祖传克隆橘子！！！.
        /// </summary>
        public static string R7 {
            get {
                return ResourceManager.GetString("R7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 打开存放橘子的仓库的大门.
        /// </summary>
        public static string R8 {
            get {
                return ResourceManager.GetString("R8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 带你重回橘子统治世界的时代.
        /// </summary>
        public static string R9 {
            get {
                return ResourceManager.GetString("R9", resourceCulture);
            }
        }
    }
}
